bootstrap added + css refactor
zbigniewkuminski/hangman pull request #4
Opened 2021-02-18 17:23 UTC by zbigniewkuminski

2021-02-25 17:00 UTC, saurongrajewo10 commented on src/components/AddPlayerToScoreboard/AddPlayerToScoreboard.js
> +              >X</button>
X button is not aligned to left side of the modal. Also in lower resolution X is displayed below header.

2021-02-25 18:01 UTC, saurongrajewo10 commented on src/components/MainPage/MainPage.js
> +      <div className="row justify-content-center">
I would like to add a question, how does 'row' class work when it is not mentioned in MainPage.css? Also How 3 classNames are merged?

2021-03-01 16:04 UTC, saurongrajewo10 requested changes
Need work

2021-03-01 17:32 UTC, saurongrajewo10 approved these changes

2021-03-11 17:02 UTC, closed without merging

2021-03-11 17:03 UTC, zbigniewkuminski commented
Merged manually